pipeline {
    agent any
    environment {
        MAVEN_PATH = 'k8e-jk-git/pom.xml'
    }
    stages {
        stage('Build') {
            steps {
				withMaven(mavenSettingsConfig: "$(JENKINS_HOME)/.m2") {
					sh "mvn clean -f ${MAVEN_PATH} install"
				}
            }
            post {
                success {
                    echo "DONE"
                }
            }
        }
    }
}
