pipeline {
    agent any
    tools {
	maven 'maven-361'
	java 'java-11'
    }
    environment {
        MAVEN_PATH = 'k8e-jk-git/pom.xml'
    }
    stages {
    	stage("check version") {
	    steps {
		sh 'java -version'
		sh 'mvn -version'
	    }	
	}
        stage("Clean") {
            steps {
                sh "mvn -f  ${MAVEN_PATH} clean"
            }
        }
        stage('Build') {
            steps {
                sh "mvn -f  ${MAVEN_PATH} install"
            }
            post {
                success {
                    echo "DONE"
                }
            }
        }
    }
}
