pipeline {
    agent any
    environment {
		fileTarget = 'demo.war'
        MAVEN_PATH = 'k8e-jk-git/pom.xml'
		mvnDir = '/var/jenkins_home/tools_jk/apache-maven-3.6.1/bin/'
		targetDir = 'k8e-jk-git/target/${fileTarget}'
		destinationDir = '../../tools_jk/build/'

    }
	
	tools {
		jdk 'jdk11' 
		maven 'maven361'
	}
	
    stages {
		stage('test-version') {
			steps {
				script {
					try {
						cm "java -version"
						cm "mvn -version"
					} catch (err) {
						echo err.getMessage()
						echo "No detect version"
					}
				}
			}
		}
		stage('Clean') {
			steps {
				echo "${mvnDir}"
				cm "${mvnDir}mvn -f ${MAVEN_PATH} clean"
			}
		}
        stage('Build') {
            steps {
				cm "${mvnDir}mvn -f ${MAVEN_PATH} install"
            }
            post {
                success {
                    echo "BUILD DONE"
                }
            }
        }
		stage('Copy') {
            steps {
				echo "Target folder: ${targetDir}"
				echo "Destination folder: ${destinationDir}"
				cm "mv ${targetDir} ${destinationDir}"
            }
            post {
                success {
                    echo "COPY DONE"
                }
            }
        }
    }
	
	def cm(cmd) {
		sh('#!/bin/sh -e\n' + cmd)
	}
}
